name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * * *" # See https://crontab.guru/#0_7,9,11,17,20_*_*_*

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    env:
      COMMIT_COUNT: 0
      MAX_COMMIT: 5

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          if [ $COMMIT_COUNT -lt $MAX_COMMIT ]; then
            set -o pipefail
            git config --global --add safe.directory /github/workspace
            git config --local user.email "ariapratama.2002@gmail.com"
            git config --local user.name "DaNgak"
            git config --global --add safe.directory /github/workspace
            git add -A

            arr=("chore(bot): 😂 auto commit" "chore(bot): 😱 auto commit" "chore(bot): 👿 auto commit" "chore(bot): 💩 auto commit" "chore(bot): 🙏 auto commit" "chore(bot): 🙈 auto commit" "chore(bot): 🐐 auto commit" "chore(bot): 🤖 auto commit" "chore(bot): 🟩 auto commit" "chore(bot): 👻 auto commit")

            rand=$[$RANDOM % ${#arr[@]}]

            git commit -m "${arr[$rand]}"

            COMMIT_COUNT=$((COMMIT_COUNT + 1))
          else
            echo "Maximum number of commits reached for today."
          fi

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
